[tool.poetry]
name = "momshelperquart"
version = "0.1.0"
description = "This goal of this project is to alleviate the mother's workload."
authors = ["arfiligol <arfiligol@gmail.com>"]
readme = "README.md"
packages = [{include = "momshelperquart", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
Quart = "^0.19.4"
quart-schema = "^0.18.0"
PyUpdater = "^4.0"
openpyxl = "^3.1.2"
pandas = "^2.1.4"
python-dotenv = "^1.0.0"
colorlog = "^6.8.0"
sqlalchemy = "^2.0.25"
numpy = "^1.26.3"
xlrd = "^2.0.1"
tox = "^4.11.4"
quart-session = "^3.0.0"
redis = "^5.0.1"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.23.3"
pyinstaller = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "momshelperquart.run:run"

[tool.pytest.ini_options]
asyncio_mode = "auto"